name: Deploy-Test

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          password : ${{ secrets.PASSWORD }}
          script: sh /home/${{ secrets.USERNAME }}/git/deploy.sh